#!/usr/bin/env python3
"""
Test script to verify the Slack bot's PDF generation with table rendering
"""

import sys
import os

# Add the src directory to the path
sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))

from cogniquery_crew.tools.pdf_generator import EnhancedPDFGenerator, TLDRExtractor

def test_slack_bot_pdf_features():
    """Test the specific features used by the Slack bot"""
    
    print("🤖 Testing Slack Bot PDF Generation Features...")
    
    # Simulate the type of report the CogniQuery crew generates
    sample_report = """# CogniQuery Analysis Report

## TLDR
- **Key Finding 1**: Southeast Asia region showing significant profit decline
- **Key Finding 2**: High discount rates correlating with negative margins  
- **Key Finding 3**: Malaysia and Singapore showing different performance patterns
- **Recommendation**: Investigate discount policies and regional pricing strategies

## Executive Summary

Our analysis of Southeast Asia performance reveals critical issues requiring immediate attention.

## Supporting Evidence

### Aggregated Metrics by Region (Past 12 Months)

| Region Name | Total Sales | Total Profit | Total Quantity | Avg Discount |
|-------------|-------------|--------------|----------------|--------------|
| Europe | 3,900.00 | 1,120.00 | 5 | 0.10 |
| North America | 1,250.00 | 500.00 | 12 | 0.00 |
| Southeast Asia | 8,200.00 | -520.00 | 20 | 0.34 |

### Country Breakdown - Southeast Asia

| Country | Total Sales | Total Profit | Total Quantity | Avg Discount |
|---------|-------------|--------------|----------------|--------------|
| Malaysia | 4,700.00 | -260.00 | 10 | 0.34 |
| Singapore | 2,300.00 | 40.00 | 6 | 0.28 |

![Regional Performance Chart](output/chart_1.png)

![Discount Impact Analysis](output/chart_2.png)

## Visual Analysis

The charts above clearly show the correlation between high discount rates and poor profitability in Southeast Asia.

## Recommendations

1. **Immediate Action Required**: Review discount policies in Southeast Asia
2. **Market Analysis**: Investigate competitive pricing pressures
3. **Performance Monitoring**: Implement monthly tracking for the region

---
*Report generated by CogniQuery AI Assistant*
"""

    print("📊 Testing TLDR extraction...")
    extractor = TLDRExtractor()
    tldr = extractor.extract_tldr(sample_report)
    print(f"✅ TLDR extracted ({len(tldr)} characters)")
    print(f"   Preview: {tldr[:100]}...")
    
    print("\n📄 Testing PDF generation with tables and images...")
    generator = EnhancedPDFGenerator()
    
    try:
        pdf_bytes = generator.create_pdf(sample_report)
        pdf_path = "output/slack_bot_test_report.pdf"
        
        with open(pdf_path, 'wb') as f:
            f.write(pdf_bytes)
        
        print(f"✅ Slack bot PDF generated: {pdf_path}")
        
        # Check file size and content
        file_size = os.path.getsize(pdf_path)
        print(f"📊 PDF file size: {file_size:,} bytes")
        
        if file_size > 100000:  # Should be substantial with images and tables
            print("🎉 PDF contains rich content (images + formatted tables)!")
        elif file_size > 30000:
            print("✅ PDF contains good content (likely formatted tables)")
        else:
            print("⚠️  PDF might be missing some formatting")
            
        # Verify chart files exist (they should from previous tests)
        chart_files = generator.get_chart_files()
        print(f"📈 Found {len(chart_files)} chart files for embedding")
        
        return True
        
    except Exception as e:
        print(f"❌ Slack bot PDF generation failed: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    success = test_slack_bot_pdf_features()
    if success:
        print("\n🎉 Slack bot PDF generation test completed!")
        print("✅ Tables should now render properly in Slack bot PDFs")
        print("✅ Images are embedded correctly")
        print("✅ TLDR extraction works for Slack messages")
        print("\n💬 The Slack bot is ready to generate enhanced PDFs with proper table formatting!")
